version: '3'
services:
  app:
    build: .
    container_name: backend-tesis
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"
      - "5555:5555"
    restart: always
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=tesis

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tesis
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
